apiVersion: v1
kind: Service
metadata:
  name: bentopdf
  annotations:
    tailscale.com/hostname: bentopdf
spec:
  selector:
    app.kubernetes.io/name: bentopdf
  ports:
    - name: http
      port: 80
      targetPort: http
