name: wsn-stacks
working_dir: stacks
auto_discovery: true
environment:
  PUID: 1000
  PGID: 1000
  UMASK: 002
  TZ: Asia/Jakarta
  # Host mount binding
  APPS_DATA_ROOT: /opt/homelab/apps
  MEDIA_DATA_ROOT: /opt/homelab/media
