apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - jellyfin
  - seerr
  - radarr
  - sonarr
  - bazarr
  - prowlarr
  - flaresolverr
  - profilarr
  - decypharr
configMapGenerator:
  - name: media-env
    literals:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: media
patches:
  - target:
      kind: Service
    patch: |-
      - op: add
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /spec/loadBalancerClass
        value: tailscale
      - op: add
        path: /metadata/annotations/tailscale.com~1proxy-group
        value: homelab-ingress
