services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    labels:
      - "tsbridge.enabled=true"
      - "tsbridge.service.name=jellyfin"
      - "tsbridge.service.port=8096" 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - jellyfin-config:/config
      - jellyfin-data:/data
    ports:
      - 8096:8096
    networks:
      - tsbridge
    restart: unless-stopped

volumes:
  jellyfin-config:
  jellyfin-data:

networks:
  tsbridge:
    external: true

