services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - jellyconf:/config
      - /mnt:/mnt:rshared
      - /data/media:/data
    restart: unless-stopped
  
  stash:
    image: stashapp/stash:latest
    ports:
      - 9999:9999
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/apps/stash/config:/root/.stash
      - /opt/apps/stash/metadata:/metadata
      - /opt/apps/stash/cache:/cache
      - /opt/apps/stash/blobs:/blobs
      - /opt/apps/stash/generated:/generated
      - /data/media:/data
      - /mnt:/mnt:rshared
    restart: unless-stopped
  
  whisparr:
    image: ghcr.io/hotio/whisparr:v3
    ports:
      - 6969:6969
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Jakarta
      - WEBUI_PORTS=6969/tcp 
    volumes:
      - whispconf:/config
      - /data:/data
      - /mnt:/mnt:rshared
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    dns:
      - 1.1.1.1
      - 9.9.9.9
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - prowconf:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    dns:
      - 1.1.1.1
      - 9.9.9.9
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Jakarta
    ports:
      - 8191:8191
    restart: unless-stopped

  decypharr:
    image: cy01/blackhole:latest
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse:rwm
    security_opt:
      - apparmor:unconfined
    ports:
      - 8282:8282
    volumes:
      - decyconf:/app
      - /mnt:/mnt:rshared
      - /data/debrid:/data/debrid
    restart: unless-stopped

volumes:
  jellyconf:
  jellydata:
  whispconf:
  whispdata:
  prowconf:
  decyconf:
