services:
  qbittorrent-nox:
    image: qbittorrentofficial/qbittorrent-nox:latest
    labels:
      - "tsbridge.enable=true"
      - "tsbridge.services.port=8080"
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8080:8080/tcp
    volumes:
      - qbittorrent-config:/config
      - qbittorrent-downloads:/downloads
    environment:
      - QBT_LEGAL_NOTICE=confirm
      - QBT_TORRENTING_PORT=6881
      - QBT_WEBUI_PORT=8080
    networks:
      - tsbridge
    restart: unless-stopped

volumes:
  qbittorrent-config: 
  qbittorrent-downloads: 
    driver: local
    driver_opts:
      type: nfs
      o: "addr=100.95.209.64,nolock,soft,rw"
      device: ":/mnt/HDD1024/data/torrents"


networks:
  tsbridge:
    external: true

