apiVersion: v1
kind: Service
metadata:
  name: profilarr
  annotations:
    tailscale.com/hostname: profilarr
spec:
  selector:
    app.kubernetes.io/name: profilarr
  ports:
    - name: http
      port: 6868
      targetPort: http
