apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - namespace.yaml
  - homepage
  - bentopdf
  - jobops
configMapGenerator:
  - name: platform-env
    literals:
      - TZ=Asia/Jakarta
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: platform
patches:
  - target:
      kind: Service
    patch: |-
      - op: add
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /spec/loadBalancerClass
        value: tailscale
      - op: add
        path: /metadata/annotations/tailscale.com~1proxy-group
        value: homelab-ingress
