apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
stringData:
  client_id: ENC[AES256_GCM,data:gYtWtQCGlYxefeh4b7NGBVk=,iv:wrqXZtD3j6pnhzZwD8Rk9Ghhn3Ycmk4KPDXU2ZSmdk4=,tag:gNDlybpcK//CFGR5/WGHjw==,type:str]
  client_secret: ENC[AES256_GCM,data:ToD7YqOST9tQ0H/SXL6ljn3NApatN0pevHNilat5DEbt/6Qdassam4b3QCs8tLvLcWeyVPdG96UijgqyeE1CSw==,iv:RZRMEMWh9aBorUsOKY2ss3cgyKTtGjtgiQOGlz0ia4M=,tag:1cszaltvr+xagnoHrN2I0w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQnFGS0c3SmMrNkEveUVN
        RmRtcjF2K3dlaE5UY2IzVlBDRWxtOUs5Wno4CkY5bGU5b3dvcVJOTGNYeU5vaTY4
        RzhEVCtQdUVxaFNncmc2Z2NMeFIvWWcKLS0tIHFvWFh5Y0h0M21SVGlGMmRPM1Zn
        ckplRGIzQnVlb0tDbk1hOElnd1krMjQKunyC9U9ijhNvFlvLeos+CwHrGbwl7tU9
        r8O+Rr2legEw7ZR6w5dkD+mpjC9bi94YAv9QDByRrBYNMLwTC0Czbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1dszs06l25zwu6rcsja47u60t2n7axqmkqztuhpf8f078tp52mdrqt9ptkv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T10:40:41Z"
  mac: ENC[AES256_GCM,data:1sWt1ER54oBn9BdAvMA8NBUhHKq6PFISNlRnUUjFSEwgskxD6GITXo1aITpuqhtCtYEmLMbzoEFhHG3DDTLB2NJmz21HRyAkUg71ll0PjnQKutDe/25LHGIjSY6+YSKa5IFVYsW2mO2XCtF3zw0Gnc/hzxBtH/Q5j9dk35/dnwY=,iv:mAL/x7uJV6GprPDakz/QrPlb34P3CnBNkjoWztXhL0g=,tag:FPIbnVCm9unenQRm38OEZA==,type:str]
  version: 3.13.1
