apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:oEiS1ZYPoniYS8hZ0/J34ClpQ4fO,iv:ZjUaD+CS8b8OEWIsPvaYOv7ZT4Zx4s7JPShA4vRuR+A=,tag:pKNWKpVc5e7Gm3k3kkg38Q==,type:comment]
    HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:MgSW8fZdcGr5TIXwPis1WA==,iv:vLOdSpKKzJOIHmjTHH1j//Per94cTh5B1rKMjsmMBfU=,tag:nUrZm3/2nrzvlfyJPb2HWg==,type:str]
    HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:AdFi0b0lVWcyQI8w4U91Gd2sWFdsUDox1Ow2i0X9Rrc/9/Bc,iv:5lo3iRXlAv2/J7gmir/UcxMI0zsB3/GckY+3vt7y5Io=,tag:PihYoRB/tpkA72Odvx8Jpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNWQ1cWIrVWhXbXhUT2VL
            OUZQVE5QZXduV2d5WUExNG9jekgzSndEZWtRCm5OVXNIQXhtQnFrNnNiNjVicnFk
            ZkZKNGZWYWtpM01qak5nWmJZMTFtQm8KLS0tIFFoR3JzTlFyK0RJV05FYStRU1g3
            aDZvUEtCM0F3eUcvNDBTTTNMWVRhOW8K7YPdIWSZkrPjF0LO8fLihAPkS4bpbNSq
            LQa6HY432kOnO304RNDvPhdOB0Z/tnOYUArl1z94e5xhdHKUliCQfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dszs06l25zwu6rcsja47u60t2n7axqmkqztuhpf8f078tp52mdrqt9ptkv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T02:49:27Z"
    mac: ENC[AES256_GCM,data:mqgJl5HyanaCAnzRWmXWfuy9MoqFqRHDgt3VCCtZhXS477lqvrklof98Jo5zbmx5PXQav49QxiS7fLaW9/XqXcufOt/R9I2L3wLCbgksBUL0RDtRZGGqqusbdNPw27KeH7Rwn5Zm5LfqwMBDkyCiYJxxIvSxN8YLJpuWqEzSOlw=,iv:2Dj9tWkgIt1LyYVQh5vGDw7RDGCFZFe5h3bW3h/7NWo=,tag:16x51PuTxBVSdRNcRQjDMw==,type:str]
    version: 3.13.1
