apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
type: Opaque
stringData:
    HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:xJPbfSUQGHNT51GHUAX1cg==,iv:uDgO32Gv1JLEBKzYFcjD8xmzDdTI49gRv4kqep5ej4s=,tag:MZArdPrA0g8yArcfFi...
    HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:kDDtER9Lj1BbsaOdWeXVkBB8f8wmVzGeEtu9loi1l8GuJK9L,iv:QC8i71f/qUf7i/cM+gPYjQeipfvmBPXEVEsQIPErte...
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteXVDYUxjQUVoM3BvT2JH
            eGhtTFBrdThzc05EbWM1dlJ4MlQ5MWQ0c1FZCnRyeWdBU3dlTTJhaWFPeWllWnBy
            RStOTTg1dVJVTFRpOUkxMUcyd2ZQU2MKLS0tIHZHRituMmZ2blpxZ0tIU01hN21O
            M3I0WVdYeW82NnVpZHc3UXh4VUZZRG8KhwgCAbD9VVtDFvm0CcTFYU53fFYsubIB
            BG+ORA7NmxTeI17n+pR+aUtgVPfIG73jTTRtv5SEeKs7Soyu+btqCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dszs06l25zwu6rcsja47u60t2n7axqmkqztuhpf8f078tp52mdrqt9ptkv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T03:29:58Z"
    mac: ENC[AES256_GCM,data:Z1CFA1FpknsUHypw0vHUERS9fNVFdD/fvvYFLL9+OQOuSiw6gv57SC9wJydBXjcTJs2J6nsCJOMEgOvyztWdcv2nTFLrNMXJjLaFMxIhcWdL77pJ+clL7I...
    version: 3.13.1
