apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
type: Opaque
stringData:
    HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:yUkUItV6HNtbWQcaFuniXQ==,iv:t0KrzAorZ+dLe+m9DWjBgim6rGpeEzZOQ21HsD8hZcY=,tag:cRUWyj3x1/gP7Y9tOh1SzQ==,type:str]
    HOMEPAGE_VAR_PROXMOX_SECRET: ENC[AES256_GCM,data:gpIuWehnxz5/HZs0O6Qa3bEmcPsjCIueg2f1Fxcwcw9YRviz,iv:VfuCv7QKPFl00y26omCpxMmI3yu6bOJZuZP5t0Et+OM=,tag:DHnBSPHmrX/19Wk/9c948A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Skc0TFB0STc3clJKQWZF
            bnNPMGxWTitkVThOeW8vYkV5RWxBbktQdURVCmtQK3p3cW53Q284d044MjRaUUNR
            dDdTTFQ3N0dISFhrSTArQWdRakhGcWMKLS0tIFlNMVVLaDRCU2M4c21xME1XZ3BR
            YmZEa1pVUUE1d0VTQncxTm96SmhIMjQKHkLAFEG31CT6v9uzjYo47HzkI3ngPT0W
            UcJjctbcGsNqYDsncWVFtw+ZPvFVt2hF+1jAeUXiwkmUB5xf9jQLpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dszs06l25zwu6rcsja47u60t2n7axqmkqztuhpf8f078tp52mdrqt9ptkv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T04:23:05Z"
    mac: ENC[AES256_GCM,data:5FO+L6o+ZQtcrHf3ODUvx9/qdF579tloV3I65e0HNVGg396qbRQ+1u//oAsHZsBB5ihiC4hYOXs0tE23FXzw3hHucgYZbhl55y9iGHfQGuJ5x7g9ZTz+jRfETjqTNrw827cE/yjyi+Vh2PnoZ3AQQUBcMTSk1Ri9/7zfnj3/NIg=,iv:qOalIAhVZ+cmnJv1GsPzTx7jTIBpEravHGUFeyPqxX8=,tag:3xf5kZUvCOrTvftjqt7uUA==,type:str]
    version: 3.13.1
