apiVersion: v1
kind: Service
metadata:
  name: radarr
  annotations:
    tailscale.com/hostname: radarr
spec:
  selector:
    app.kubernetes.io/name: radarr
  ports:
    - name: http
      port: 7878
      targetPort: http
