anchors = ["/data"]

[triggers.radarr]
type = "radarr"

[triggers.radarr.rewrite]
from = "^/data/media/"
to = "/data/"

[triggers.radarr.timer]
wait = 5

[triggers.sonarr]
type = "sonarr"

[triggers.sonarr.rewrite]
from = "^/data/media/"
to = "/data/"

[triggers.sonarr.timer]
wait = 5

[targets.jellyfin]
type = "jellyfin"
url = "http://jellyfin:8096"
token = "REPLACE_WITH_YOUR_JELLYFIN_API_TOKEN"
